// Vendor-defined ("standard") event names and event parameters, from each vendor's
// documentation. Everything else a website sends in a vendor's event-data namespace is
// "custom". Vendors whose event names come from per-account configuration (LinkedIn, X,
// Floodlight, Google Ads, Adobe, Criteo, Taboola, Outbrain) have no event list.

// Meta Pixel reference: standard events plus PageView, the base Pixel event. Case-sensitive.
export const metaStandardEvents = ['PageView','ViewContent','Search','AddToCart','AddToWishlist','InitiateCheckout','AddPaymentInfo','Purchase','Lead','CompleteRegistration','Contact','CustomizeProduct','Donate','FindLocation','Schedule','StartTrial','SubmitApplication','Subscribe'];

const events = {
  Meta: { names: metaStandardEvents },
  // Recommended events, plus automatically collected and enhanced measurement events. Case-sensitive.
  GA4: { names: [
    'ad_impression','earn_virtual_currency','generate_lead','join_group','login','purchase','refund','search','select_content','share','sign_up','spend_virtual_currency','tutorial_begin','tutorial_complete',
    'add_payment_info','add_shipping_info','add_to_cart','add_to_wishlist','begin_checkout','remove_from_cart','select_item','select_promotion','view_cart','view_item','view_item_list','view_promotion',
    'qualify_lead','disqualify_lead','working_lead','close_convert_lead','close_unconvert_lead',
    'level_end','level_start','level_up','post_score','unlock_achievement',
    'click','file_download','first_visit','form_start','form_submit','page_view','scroll','session_start','user_engagement','video_complete','video_progress','video_start','view_search_results',
  ] },
  // Current standard events, Pageview from ttq.page(), and earlier standard events that
  // existing installs still send (CompletePayment, PlaceAnOrder, ClickButton).
  TikTok: { names: ['Pageview','AddPaymentInfo','AddToCart','AddToWishlist','ApplicationApproval','CompleteRegistration','Contact','CustomizeProduct','Download','FindLocation','InitiateCheckout','Purchase','Schedule','Search','StartTrial','SubmitApplication','SubmitForm','Subscribe','ViewContent','CompletePayment','PlaceAnOrder','ClickButton'] },
  // Event codes are lowercase; "custom" is Pinterest's custom event.
  Pinterest: { names: ['pagevisit','viewcategory','search','addtocart','checkout','watchvideo','signup','lead','addpaymentinfo','addtowishlist','initiatecheckout','subscribe','viewcontent','contact','schedule','findlocation','customizeproduct','submitapplication','starttrial'], ignoreCase: true },
  // CUSTOM_EVENT_1 to CUSTOM_EVENT_5 are Snap's custom events.
  Snapchat: { names: ['PAGE_VIEW','VIEW_CONTENT','ADD_CART','START_CHECKOUT','PURCHASE','SIGN_UP','ADD_BILLING','SEARCH','SAVE','SUBSCRIBE','AD_CLICK','AD_VIEW','COMPLETE_TUTORIAL','LEVEL_COMPLETE','INVITE','LOGIN','SHARE','RESERVE','ACHIEVEMENT_UNLOCKED','ADD_TO_WISHLIST','SPENT_CREDITS','RATE','START_TRIAL','LIST_VIEW','APP_OPEN','APP_INSTALL'] },
  // "Custom" is Reddit's custom event type.
  'Reddit Ads': { names: ['PageVisit','ViewContent','Search','AddToCart','AddToWishlist','Purchase','Lead','SignUp'] },
  // UET page loads are the base event; every event action (ea) is a UET custom event.
  'Microsoft Ads': { names: ['PageView'] },
  // Events generated by the SDK itself (autocapture, identify, revenue) rather than by the website.
  Amplitude: { test: name => name.startsWith('[Amplitude] ') || ['$identify', '$groupidentify', 'revenue_amount'].includes(name) },
};

// Returns 'standard', 'custom', or null when the vendor has no standard event list.
export function standardEventType(platform, name) {
  const catalog = events[platform];
  if (!catalog || typeof name !== 'string') return null;
  const standard = catalog.test ? catalog.test(name)
    : catalog.ignoreCase ? catalog.names.includes(name.toLowerCase()) : catalog.names.includes(name);
  return standard ? 'standard' : 'custom';
}

// Standard event parameters, keyed by the parameter name after fieldKey() strips the
// vendor's transport prefix (cd[...], ep./epn., properties., ed[...], and so on).
const metaStandardProperties = ['content_category','content_ids','content_name','content_type','contents','currency','num_items','predicted_ltv','search_string','status','value'];
const fields = {
  Meta: metaStandardProperties,
  // GA4 recommended event parameters; cu is the currency parameter and pr1, pr2, … are items.
  GA4: ['currency','value','transaction_id','coupon','shipping','tax','affiliation','payment_type','shipping_tier','items','item_list_id','item_list_name','creative_name','creative_slot','promotion_id','promotion_name','location_id','search_term','method','content_type','item_id','group_id','level','level_name','character','score','success','achievement_id','virtual_currency_name','lead_source'],
  'Google Ads': ['value','currency','currency_code','transaction_id','oid'],
  TikTok: ['content_type','content_ids','content_id','content_name','content_category','contents','currency','value','quantity','price','description','query','search_string','order_id'],
  Pinterest: ['value','currency','order_quantity','order_id','event_id','promo_code','property','search_query','video_title','lead_type','line_items','product_name','product_id','product_category','product_variant_id','product_variant','product_price','product_quantity','product_brand'],
  Snapchat: ['price','currency','transaction_id','item_ids','item_category','description','num_items','number_items','payment_info_available','search_string','sign_up_method','level','success','client_dedup_id'],
  'Reddit Ads': ['value','value_decimal','currency','item_count','itemCount','products','conversion_id','conversionId'],
  // UET custom event fields: category, action, label, value, and variable revenue and currency.
  'Microsoft Ads': ['ec','ea','el','ev','gv','gc'],
  'X Ads': ['value','currency','tw_sale_amount','tw_order_quantity'],
  'Google Floodlight': ['ord','qty','cost'],
  'Adobe Analytics': ['events','products'],
  Taboola: ['revenue','currency'],
  Outbrain: ['orderValue','orderId','currency'],
  // HTTP API revenue fields; event_properties are the website's own.
  Amplitude: ['revenue','price','quantity','productId','revenueType'],
  // Tracker protocol fields for structured events and transactions.
  Snowplow: name => /^(?:se|tr|ti)_/.test(name),
};

// The parameter name inside a vendor's event-data namespace, or null for transport and
// identity fields outside it.
function fieldKey(platform, name) {
  const text = String(name);
  const strip = key => key?.replace(/\[\d+\]$/, '') ?? null;
  switch (platform) {
    case 'Meta': return text.match(/^cd\[([^\]]+)\]/)?.[1] ?? null;
    case 'GA4': return /^pr\d+$/.test(text) ? 'items' : text === 'cu' ? 'currency' : text.match(/^epn?\.(.+)$/)?.[1] ?? null;
    case 'TikTok': return strip(text.match(/(?:^|\.)properties\.([^.[]+(?:\[\d+\])?)/)?.[1]);
    case 'Pinterest': return text.match(/^ed\[([^\]]+)\]/)?.[1] ?? null;
    case 'Snapchat': return strip(text.match(/(?:^|\.t\.)([a-z_]+(?:\[\d+\])?)$/)?.[1]);
    case 'Reddit Ads': return text.match(/^(?:event_metadata\.)?([^.[]+)/)?.[1] ?? null;
    default: return text;
  }
}

export function isStandardField(platform, name) {
  const standard = fields[platform];
  const key = fieldKey(platform, name);
  if (!standard || !key) return false;
  return typeof standard === 'function' ? standard(key) : standard.includes(key);
}
