import { chromium } from 'playwright';
import { resolve } from 'node:path';
import { mkdtemp, readFile, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import assert from 'node:assert/strict';
const extension = resolve('extension');
const profile = await mkdtemp(`${tmpdir()}/pixelmonitor-extension-`);
const context = await chromium.launchPersistentContext(profile, {
  channel: 'chromium', headless: true,
  args: [`--disable-extensions-except=${extension}`, `--load-extension=${extension}`],
});
try {
  const worker = context.serviceWorkers()[0] || await context.waitForEvent('serviceworker');
  const id = new URL(worker.url()).host;
  await context.route('https://audit-fixture.test/**', route => route.fulfill({ contentType: 'text/html', body: '<h1>Website fixture</h1><button data-testid="filters">Open filters</button><button>Add to cart</button>' }));
  const website = await context.newPage();
  await website.goto('https://audit-fixture.test');
  const tabId = await worker.evaluate(async () => (await chrome.tabs.query({})).find(t => t.url?.startsWith('https://audit-fixture.test')).id);
  const panel = await context.newPage();
  await panel.setViewportSize({width:390,height:900});
  await panel.goto(`chrome-extension://${id}/panel.html`);
  assert.equal(await panel.locator('.brand-copy h1').innerText(), 'Pixel Inspector');
  assert.equal(await panel.locator('.brand-copy p').innerText(), 'by PixelMonitor');
  const feedbackLink = panel.getByRole('link', {name:'Send feedback'});
  assert.equal(await feedbackLink.innerText(), 'Send feedback');
  assert.equal(await feedbackLink.getAttribute('href'), 'mailto:mayur@pixelmonitor.app?subject=Pixel%20Inspector%20feedback');
  assert.equal(await panel.getByRole('link', {name:'Privacy'}).getAttribute('href'), 'privacy.html');
  assert.equal(await panel.locator('#start').count(), 0);
  const send = (type, data = {}) => panel.evaluate(async ({type, data, defaultTabId}) => chrome.runtime.sendMessage({type, tabId: defaultTabId, ...data}), {type, data, defaultTabId:tabId});
  await panel.waitForFunction(() => document.querySelector('#status')?.textContent === 'Inspecting');
  const started = await send('get');
  assert.equal(started.audit.recording, true);
  assert.equal(await panel.locator('#stop').innerText(), 'Pause');
  assert.equal(await panel.locator('#clear').innerText(), 'Clear');
  assert.equal(started.audit.actions[0].id, 'A1');
  assert.equal(started.audit.actions[0].name, 'Started on /');
  await website.reload();
  await panel.waitForTimeout(500);
  assert.equal((await send('get')).audit.actions.length, 1);
  await website.getByRole('button', {name:'Open filters'}).click();
  await panel.waitForFunction(async tabId => (await chrome.storage.session.get('audits')).audits[tabId].actions.some(action => action.action === 'click'), tabId);
  const genericClick = (await send('get')).audit.actions.find(action => action.action === 'click').replay;
  assert.deepEqual({role:genericClick.role,name:genericClick.name,selector:genericClick.selector,tag:genericClick.tag}, {role:'button',name:'Open filters',selector:'button[data-testid="filters"]',tag:'button'});
  await website.getByRole('button', {name:'Add to cart'}).click();
  await panel.waitForFunction(async tabId => (await chrome.storage.session.get('audits')).audits[tabId].actions.some(action => action.action === 'cart'), tabId);
  // Drive Chrome's actual webRequest lifecycle while fulfilling locally so no test pixel leaves the browser.
  await context.route('https://www.facebook.com/tr/**', route => route.fulfill({ status: 204, body: '' }));
  await website.evaluate(() => { const image = new Image(); image.src='https://www.facebook.com/tr/?id=123&ev=AddToCart&cd[content_category]=Shoes&test_mode=enabled&customer_email=person%40example.com'; });
  await panel.waitForFunction(async tabId => (await chrome.storage.session.get('audits')).audits[tabId].events.length === 1, tabId);
  await website.bringToFront();
  await panel.reload();
  assert.deepEqual(await panel.locator('#filter option').allTextContents(), ['All vendors', 'Meta']);
  await panel.locator('#expandAll').click();
  await panel.waitForTimeout(2500);
  assert.equal(await panel.locator('#journey details').evaluateAll(nodes => nodes.every(node => node.open)), true);
  await panel.locator('#collapseAll').click();
  await panel.waitForTimeout(2500);
  assert.equal(await panel.locator('#journey details').evaluateAll(nodes => nodes.every(node => !node.open)), true);
  const cartAction = panel.locator('#journey li').filter({hasText:'Clicked “Add to cart”'});
  assert.match(await cartAction.innerText(), /Clicked button[\s\S]*Add to cart[\s\S]*1 tracking event after this action/);
  await cartAction.locator('.action-tracking > summary').click();
  const vendorSummary = cartAction.locator('.action-vendor-group > summary');
  assert.match(await vendorSummary.innerText(), /Meta · 1 pixel ID · 1 event/);
  await vendorSummary.click();
  const destinationSummary = cartAction.locator('.action-destination-group > summary');
  assert.match(await destinationSummary.innerText(), /Pixel ID · 123 · 1 event/);
  await destinationSummary.click();
  assert.match(await cartAction.locator('.action-event-list').innerText(), /Meta · AddToCart[\s\S]*Destination 123/);
  const firstDetails = panel.locator('[data-event-id="E1"] > details');
  await firstDetails.locator(':scope > summary').click();
  assert.equal(await firstDetails.locator(':scope > .event-explanation, :scope > dl').count(), 0);
  assert.deepEqual(await firstDetails.locator('.payload-fields h4').allTextContents(), ['Payload fields']);
  assert.match(await firstDetails.locator(':scope > summary').innerText(), /View payload · 5 fields/);
  assert.match(await firstDetails.locator('.payload-fields').innerText(), /Required[\s\S]*Custom[\s\S]*Other[\s\S]*id[\s\S]*123[\s\S]*ev[\s\S]*AddToCart/);
  assert.match(await firstDetails.locator('.payload-fields').innerText(), /cd\[content_category\][\s\S]*Shoes[\s\S]*test_mode[\s\S]*enabled[\s\S]*customer_email[\s\S]*person@example.com/);
  assert.deepEqual(await firstDetails.locator('.payload-row').evaluateAll(rows => rows.map(row => row.dataset.kind)), ['required', 'required', 'custom', 'other', 'other']);
  assert.equal(await firstDetails.locator('.raw-data').count(), 0);
  await panel.locator('#search').fill('AddToCart');
  assert.equal(await panel.locator('.event').count(), 1);
  assert.equal(await panel.locator('#journey > li').count(), 1);
  assert.equal(await panel.locator('#clearSearch').isVisible(), true);
  await panel.locator('#clearSearch').click();
  assert.equal(await panel.locator('#search').inputValue(), '');
  assert.equal(await panel.locator('#clearSearch').isHidden(), true);
  assert.equal(await panel.locator('#journey > li').count(), 3);
  await panel.locator('#search').fill('AddToCart');
  await panel.locator('#search').fill('Pixel ID');
  assert.equal(await panel.locator('.event').count(), 1);
  await panel.locator('#search').fill('123');
  assert.equal(await panel.locator('.event').count(), 1);
  await panel.locator('#search').fill('content_category');
  assert.equal(await panel.locator('.event').count(), 1);
  await panel.locator('#search').fill('Shoes');
  assert.equal(await panel.locator('.event').count(), 1);
  await panel.locator('#search').fill('test_mode');
  assert.equal(await panel.locator('.event').count(), 1);
  await panel.locator('#search').fill('does-not-exist');
  assert.equal(await panel.locator('.event').count(), 0);
  assert.equal(await panel.locator('#journey > li').count(), 1);
  assert.equal(await panel.locator('#journey > li.empty').innerText(), 'No journey activity matches your search.');
  await panel.locator('#search').fill('Open filters');
  assert.equal(await panel.locator('#journey > li').count(), 1);
  assert.match(await panel.locator('#journey > li').innerText(), /Clicked “Open filters”/);
  await panel.locator('#search').fill('');
  assert.equal(await panel.locator('#journey > li').count(), 3);
  assert.equal(await panel.locator('.event').count(), 1);
  await panel.waitForTimeout(2500);
  assert.equal(await firstDetails.evaluate(node => node.open), true);
  await website.goto('https://audit-fixture.test/next');
  await website.evaluate(() => { const image = new Image(); image.src='https://www.facebook.com/tr/?id=123&ev=PageView'; });
  await panel.waitForFunction(async tabId => (await chrome.storage.session.get('audits')).audits[tabId].events.length === 2, tabId);
  await website.evaluate(() => { const image = new Image(); image.src='https://www.facebook.com/tr/?id=123&ev=Purchase&cd[value]=oops&cd[currency]=usd'; });
  await panel.waitForFunction(async tabId => (await chrome.storage.session.get('audits')).audits[tabId].events.length === 3, tabId);
  await panel.waitForFunction(() => document.querySelector('#checkSummary')?.textContent.includes('2 payload issues'));
  const purchaseCard = panel.locator('[data-event-id="E3"]');
  assert.match(await purchaseCard.locator('.check-badge').textContent(), /2 checks flagged/);
  assert.match(await purchaseCard.locator('.event-checks').textContent(), /finite numeric amount/);
  assert.equal(await purchaseCard.locator('.event-checks a').first().getAttribute('href'), 'https://developers.facebook.com/docs/meta-pixel/reference/');
  assert.equal(await panel.locator('.event.error, .event.warning').count(), 0);
  assert.equal(await firstDetails.evaluate(node => node.open), true);
  await firstDetails.locator(':scope > summary').click();
  await panel.waitForFunction(() => !document.querySelector('[data-event-id="E1"] > details')?.open);
  await panel.waitForTimeout(2500);
  assert.equal(await firstDetails.evaluate(node => node.open), false);
  const other = await context.newPage();
  await other.goto('https://audit-fixture.test/other');
  await other.evaluate(() => { const image = new Image(); image.src='https://www.facebook.com/tr/?id=456&ev=Purchase'; });
  const otherTabId = await worker.evaluate(async () => (await chrome.tabs.query({})).find(t => t.url?.includes('/other')).id);
  await panel.waitForFunction(async otherTabId => Boolean((await chrome.storage.session.get('audits')).audits[otherTabId]?.recording), otherTabId);
  assert.equal((await send('get')).audit.events.length, 3);
  assert.equal((await send('get', {tabId:otherTabId})).audit.recording, true);
  await other.evaluate(() => { const image = new Image(); image.src='https://www.facebook.com/tr/?id=456&ev=PageView'; });
  await panel.waitForFunction(async otherTabId => (await chrome.storage.session.get('audits')).audits[otherTabId].events.length === 1, otherTabId);
  assert.equal((await send('get', {tabId:otherTabId})).audit.events[0].pixelId, '456');
  await context.route('https://analytics.tiktok.com/api/v2/pixel/act', route => route.fulfill({ status: 204, body: '' }));
  await other.evaluate(() => fetch('https://analytics.tiktok.com/api/v2/pixel/act', {
    method: 'POST', mode: 'no-cors', body: JSON.stringify({
      action: 'Metadata', context: { pixel: { code: 'CTIKTOK123' } },
      auto_collected_properties: { page_trigger: 'PageView' },
    }),
  }));
  await panel.waitForFunction(async otherTabId => (await chrome.storage.session.get('audits')).audits[otherTabId].events.length === 2, otherTabId);
  const tikTok = (await send('get', {tabId:otherTabId})).audit.events.find(event => event.platform === 'TikTok');
  assert.deepEqual([tikTok.event, tikTok.pixelId], ['Auto PageView', 'CTIKTOK123']);
  assert.equal((await send('get')).audit.events.length, 3);
  await send('stop', {tabId:otherTabId});
  await send('clear', {tabId:otherTabId});
  await send('consent', {value:'Accepted during Cart'});
  const stopped = (await send('stop')).audit;
  assert.equal(stopped.events.length, 3);
  assert.equal(stopped.events[0].event, 'AddToCart');
  assert.equal(stopped.events[0].actionId, 'A3');
  assert.equal(stopped.events[0].action, 'Clicked “Add to cart”');
  assert.equal(stopped.events[0].status, 204);
  assert.equal(stopped.events[0].failed, undefined);
  assert.equal(stopped.events[0].step, undefined);
  assert.equal(stopped.recording, false);
  await website.evaluate(() => { const image = new Image(); image.src='https://www.facebook.com/tr/?id=123&ev=Purchase'; });
  await panel.waitForTimeout(300);
  assert.equal((await send('get')).audit.events.length, 3);
  await website.bringToFront();
  await panel.reload();
  assert.equal(await panel.locator('#status').innerText(), 'Paused');
  assert.equal(await panel.locator('#stop').innerText(), 'Resume');
  await panel.locator('#stop').click();
  await panel.waitForFunction(() => document.querySelector('#status')?.textContent === 'Inspecting');
  assert.equal(await panel.locator('#stop').innerText(), 'Pause');
  await panel.locator('#stop').click();
  await panel.waitForFunction(() => document.querySelector('#status')?.textContent === 'Paused');
  assert.equal(await panel.locator('.snapshot-card h2').innerText(), 'Session summary');
  assert.equal(await panel.locator('#destinationMetric + span').innerText(), 'Pixel IDs');
  assert.equal(await panel.locator('.evidence-card h2').innerText(), 'Visitor journey and pixels');
  assert.equal(await panel.locator('.export-card').isVisible(), true);
  await panel.waitForSelector('#json:enabled');
  const downloadPromise = panel.waitForEvent('download');
  await panel.locator('#json').click();
  const download = await downloadPromise;
  assert.ok(download.suggestedFilename().endsWith('report.json'));
  const reportPath = await download.path();
  assert.ok(reportPath);
  const exportedAudit = JSON.parse(await readFile(reportPath, 'utf8'));
  assert.ok(Array.isArray(exportedAudit.actions));
  assert.equal(exportedAudit.steps, undefined);
  assert.equal(exportedAudit.findings, undefined);
  assert.equal(exportedAudit.bestPractices.length, 2);
  assert.ok(exportedAudit.bestPractices.every(f => f.eventId === 'E3'));
  const htmlDownloadPromise = panel.waitForEvent('download');
  await panel.locator('#html').click();
  const htmlDownload = await htmlDownloadPromise;
  assert.match(await readFile(await htmlDownload.path(), 'utf8'), /Vendor best-practice checks/);
  const summaryDownloadPromise = panel.waitForEvent('download');
  await panel.locator('#summary').click();
  const summaryDownload = await summaryDownloadPromise;
  assert.match(await readFile(await summaryDownload.path(), 'utf8'), /Payload issue · E3/);
  await panel.evaluate(() => {
    const event = document.querySelector('[data-event-id="E3"]');
    for (let parent = event?.parentElement; parent; parent = parent.parentElement) if (parent instanceof HTMLDetailsElement) parent.open = true;
    const payload = event?.querySelector(':scope > details');
    if (payload) payload.open = true;
    window.scrollTo(0, 0);
  });
  await panel.screenshot({path: '/tmp/pixelmonitor-extension.png', fullPage:true});
  if (process.env.UPDATE_STORE_SCREENSHOT === '1') {
    await panel.setViewportSize({width:1280,height:800});
    await panel.screenshot({path: resolve('extension/store-assets/store-screenshot-1280x800.png')});
    await panel.setViewportSize({width:390,height:900});
  }
  panel.once('dialog', dialog => dialog.accept());
  await panel.locator('#clear').click();
  await panel.waitForFunction(async tabId => {
    const current = (await chrome.storage.session.get('audits')).audits[tabId];
    return current?.recording && current.events.length === 0;
  }, tabId);
  // A pixel fires during document parsing, before the document_idle observer.
  // Clear must leave recording armed so a same-URL reload captures this event.
  await context.route('https://audit-fixture.test/**', route => route.fulfill({
    contentType: 'text/html',
    body: '<img src="https://www.facebook.com/tr/?id=789&ev=PageView"><button data-testid="filters">Open filters</button>',
  }));
  const beforeReload = (await send('get')).audit.startedAt;
  await website.reload();
  await panel.waitForFunction(async tabId => (await chrome.storage.session.get('audits')).audits[tabId].events.length === 1, tabId);
  const refreshed = (await send('get')).audit;
  assert.equal(refreshed.recording, true);
  assert.equal(refreshed.startedAt, beforeReload);
  assert.equal(refreshed.events[0].pixelId, '789');
  assert.equal(refreshed.events[0].event, 'PageView');
  await website.getByRole('button', {name:'Open filters'}).click();
  await panel.waitForFunction(async tabId => (await chrome.storage.session.get('audits')).audits[tabId].actions.some(action => action.action === 'click'), tabId);
  // Also recover an absent session on same-URL reload, without a URL change.
  await send('clear');
  await website.reload();
  await panel.waitForFunction(async tabId => (await chrome.storage.session.get('audits')).audits[tabId]?.recording, tabId);
  await send('clear');
  await website.goto('about:blank');
  await website.bringToFront();
  assert.equal(await panel.locator('#status').innerText(), 'Waiting');
  await website.goto('https://audit-fixture.test/from-new-tab');
  await panel.waitForFunction(() => document.querySelector('#status')?.textContent === 'Inspecting');
  const restarted = await send('get');
  assert.equal(restarted.audit.actions[0].name, 'Started on /from-new-tab');
  await website.evaluate(() => {
    const editor = document.createElement('div');
    editor.contentEditable = 'true'; editor.textContent = 'private typed content';
    document.body.append(editor);
  });
  await website.locator('[contenteditable]').click();
  await panel.waitForFunction(async tabId => (await chrome.storage.session.get('audits')).audits[tabId].actions.length === 2, tabId);
  assert.equal(JSON.stringify((await send('get')).audit).includes('private typed content'), false);
  const privacy = await context.newPage();
  await privacy.goto(`chrome-extension://${id}/privacy.html`);
  assert.match(await privacy.locator('body').innerText(), /Limited Use/);
  await privacy.close();
  console.log('Extension smoke test passed: independent per-tab recordings, neutral evidence UI, navigation, action capture, search, exports, and clear.');
} finally { await context.close(); await rm(profile, {recursive:true, force:true}); }
